var hierarchy =
[
    [ "ArxLinLayer_t", "structArxLinLayer__t.html", null ],
    [ "binary_function", null, [
      [ "rc5_compare_key_by_value", "structrc5__compare__key__by__value.html", null ],
      [ "rc5_diff_equal_to", "structrc5__diff__equal__to.html", null ],
      [ "rc5_eq_x_params_equal_to", "structrc5__eq__x__params__equal__to.html", null ],
      [ "rc5_goup_diffs_equal_to", "structrc5__goup__diffs__equal__to.html", null ],
      [ "simon_diff_equal_to", "structsimon__diff__equal__to.html", null ],
      [ "simon_diff_graph_node_comp", "structsimon__diff__graph__node__comp.html", null ],
      [ "simon_trail_equal_to", "structsimon__trail__equal__to.html", null ],
      [ "speck_diff_equal_to", "structspeck__diff__equal__to.html", null ],
      [ "speck_trail_equal_to", "structspeck__trail__equal__to.html", null ],
      [ "struct_comp_diff_3d_dx_dy_dz", "structstruct__comp__diff__3d__dx__dy__dz.html", null ],
      [ "struct_comp_diff_3d_p", "structstruct__comp__diff__3d__p.html", null ],
      [ "struct_comp_diff_dx_dy", "structstruct__comp__diff__dx__dy.html", null ],
      [ "struct_comp_diff_hw", "structstruct__comp__diff__hw.html", null ],
      [ "struct_comp_diff_p", "structstruct__comp__diff__p.html", null ]
    ] ],
    [ "bits_t", "structbits__t.html", null ],
    [ "bsd_t", "structbsd__t.html", null ],
    [ "Correlation", "structCorrelation.html", null ],
    [ "diff_set_t", "structdiff__set__t.html", null ],
    [ "difference_t", "structdifference__t.html", null ],
    [ "Differential", "structDifferential.html", null ],
    [ "differential_3d_t", "structdifferential__3d__t.html", null ],
    [ "differential_t", "structdifferential__t.html", null ],
    [ "eq_x_params_t", "structeq__x__params__t.html", null ],
    [ "morus_diff_state_t", "structmorus__diff__state__t.html", null ],
    [ "pair_t", "structpair__t.html", null ],
    [ "rc5_enc_t", "structrc5__enc__t.html", null ],
    [ "rc5_goup_diffs_t", "structrc5__goup__diffs__t.html", null ],
    [ "rc5_interval_t", "structrc5__interval__t.html", null ],
    [ "rc5_key_t", "structrc5__key__t.html", null ],
    [ "set_t", "structset__t.html", null ],
    [ "simon_diff_graph_edge_t", "structsimon__diff__graph__edge__t.html", null ],
    [ "simon_diff_graph_node_t", "structsimon__diff__graph__node__t.html", null ],
    [ "skey_t", "structskey__t.html", null ],
    [ "unary_function", null, [
      [ "rc5_diff_hash", "structrc5__diff__hash.html", null ],
      [ "rc5_eq_x_params_hash", "structrc5__eq__x__params__hash.html", null ],
      [ "rc5_goup_diffs_hash", "structrc5__goup__diffs__hash.html", null ],
      [ "simon_diff_graph_node_alloc", "structsimon__diff__graph__node__alloc.html", null ],
      [ "simon_diff_hash", "structsimon__diff__hash.html", null ],
      [ "simon_trail_hash", "structsimon__trail__hash.html", null ],
      [ "speck_diff_hash", "structspeck__diff__hash.html", null ],
      [ "speck_trail_hash", "structspeck__trail__hash.html", null ]
    ] ]
];